[package]
name = "ata"
version = "0.1.0"
edition = { workspace = true }

[dependencies]
internal_utils = { workspace = true }
x86_64 = { workspace = true }
spin = { workspace = true }
bitflags = { workspace = true }
lazy_static = { workspace = true }
